### ISSUE TITLE
callbacks

### ISSUE THREAD

**Issue by ahundt** [titu1994/pyshac#6]
I think it isn't necessary, but I wanted to confirm, since model.fit is currently called in an [evaluate_model() function](https://github.com/titu1994/pyshac/blob/master/examples/tensorflow/mini_conv.py#L102) it could be re-initialized each time anyway so I guess it isn't a big deal in any case, they can just be created there.

**Comment by titu1994** [comment]
I've been toying with the idea of call backs. Haven't found a useful case yet. Can you elaborate where call backs will be useful ?

**Comment by titu1994** [comment]
Hmm interesting. I'll think about the best way to implement call backs in the coming weeks and try to get it done.

**Comment by titu1994** [comment]
@ahundt Callbacks are now supported, as of [v0.3.1](https://github.com/titu1994/pyshac/releases/tag/v0.3.1). They are based almost entirely on Keras' callbacks, so it should be quite familiar. 

Like Keras, `History` is returned for all `fit` or `fit_dataset` calls now, and CSVLogger can write most of the content into a file. `history.history` is used to extract all of the values of the History object, similar to Keras.

`History` also will contain the `model` key in its dictionary, which are the XGBoost models generated, along with some meta information useful for the model such as the worker ids, the parameters at each epoch and the evaluated scores for them, along with a few other things which I thought might be useful.

**Comment by ahundt** [comment]
Awesome 👍

**Comment by ahundt** [comment]
Is there a documentation website? I only just found out that there are other documentation pages that aren't linked from the main readme.md. (like callbacks)

**Comment by titu1994** [comment]
http://titu1994.github.io/pyshac/

Readthedocs has a really horrible format and doesn't support this style, but I guess I'll just have to compromise and host it there as well.

**Comment by ahundt** [comment]
you could also add some documentation link as the link github lets you add to the very top of the page by the title
